"""GS-Diff distillation from inpainted pseudo-ground-truth views.

Renders the current Gaussian splat from inpainted viewpoints, computes
L1+SSIM loss against the inpainted targets (excluding hallucinated
pixels identified by LPIPS thresholding), and returns updated
Gaussians. This is analogous to Stage 6 optimisation but operates on
pseudo-views generated by the diffusion inpainting model.
"""

from __future__ import annotations

import logging

import numpy as np

from sphereforge.common.metrics import compute_ssim

logger = logging.getLogger("sphereforge.stage07.distillation")


def distill_inpaint(
    gaussians: dict,
    novel_views: list[dict],
    lpips_mask: np.ndarray | None = None,
    l1_weight: float = 0.8,
    ssim_weight: float = 0.2,
) -> dict:
    """Optimise Gaussians against inpainted pseudo-ground-truth views.

    For each novel view, the function computes an L1 + SSIM loss between
    a (simulated) render and the inpainted target image, masked by the
    LPIPS hallucination filter. The Gaussians are updated via gradient
    descent on the combined loss.

    In this stub implementation, the rendering is approximated by
    projecting Gaussian means and accumulating colours. A full
    implementation would use the differentiable rasteriser from Stage 6.

    Args:
        gaussians: Dictionary with keys ``positions`` (N,3), ``colors``
            (N,3), ``opacities`` (N,), ``scales`` (N,3), ``rotations`` (N,4),
            and optionally ``sh_coeffs`` (N,45).
        novel_views: List of dicts, each containing:
            - ``viewmat`` (np.ndarray): 4x4 camera extrinsic.
            - ``fov`` (float): Horizontal field of view in degrees.
            - ``height`` (int), ``width`` (int): Image dimensions.
            - ``image`` (np.ndarray): Inpainted target image (H, W, 3).
            - ``depth`` (np.ndarray, optional): Depth prior for this view.
        lpips_mask: Boolean mask of shape (H, W) where ``True`` = exclude
            from training (hallucinated). If ``None``, no masking.
        l1_weight: Weight for the L1 loss component. Default 0.8.
        ssim_weight: Weight for the SSIM loss component. Default 0.2.

    Returns:
        Updated gaussians dict with adjusted positions, colours, and
        scales. The number of Gaussians does not change.
    """
    positions = np.asarray(gaussians["positions"], dtype=np.float32)
    colors = np.asarray(gaussians["colors"], dtype=np.float32)
    opacities = np.asarray(gaussians["opacities"], dtype=np.float32)
    scales = np.asarray(gaussians["scales"], dtype=np.float32)
    rotations = np.asarray(gaussians["rotations"], dtype=np.float32)
    sh_coeffs = gaussians.get("sh_coeffs")

    positions.shape[0]

    if not novel_views:
        logger.warning("No novel views provided for distillation")
        return gaussians

    total_loss = 0.0
    n_views = 0

    for view in novel_views:
        target_img = view.get("image")
        if target_img is None:
            logger.debug("Skipping view without target image")
            continue

        target_img = np.asarray(target_img, dtype=np.float32)
        if target_img.max() > 1.5:
            target_img = target_img / 255.0

        viewmat = np.asarray(view["viewmat"], dtype=np.float64)
        H = view.get("height", target_img.shape[0])
        W = view.get("width", target_img.shape[1])
        fov = view.get("fov", 90.0)

        # Approximate render by projecting Gaussians
        fx = (W / 2.0) / np.tan(np.radians(fov) / 2.0)
        fy = fx
        cx, cy = W / 2.0, H / 2.0

        R = viewmat[:3, :3]
        t = viewmat[:3, 3]
        cam_pos = (R @ positions.T + t[:, None]).T
        z = cam_pos[:, 2]
        visible = z > 1e-6

        if not np.any(visible):
            continue

        vis_cam = cam_pos[visible]
        vis_col = colors[visible]
        vis_opa = opacities[visible]

        px = (vis_cam[:, 0] / vis_cam[:, 2]) * fx + cx
        py = (vis_cam[:, 1] / vis_cam[:, 2]) * fy + cy

        # Sort by depth (back-to-front) for naive alpha blending
        order = np.argsort(-z[visible])
        px_sorted = px[order]
        py_sorted = py[order]
        col_sorted = vis_col[order]
        opa_sorted = vis_opa[order]

        # Normalise colours to [0, 1]
        if col_sorted.max() > 1.5:
            col_sorted = col_sorted / 255.0

        # Simple splat: accumulate colours into pixel grid
        rendered = np.zeros((H, W, 3), dtype=np.float32)
        alpha_acc = np.zeros((H, W), dtype=np.float32)

        px_int = np.clip(np.round(px_sorted).astype(int), 0, W - 1)
        py_int = np.clip(np.round(py_sorted).astype(int), 0, H - 1)

        # Back-to-front alpha blending
        for i in range(len(px_int)):
            xi, yi = px_int[i], py_int[i]
            a = float(opa_sorted[i]) * (1.0 - alpha_acc[yi, xi])
            rendered[yi, xi] += a * col_sorted[i]
            alpha_acc[yi, xi] += a

        # Clamp alpha
        alpha_acc = np.clip(alpha_acc, 0, 1)

        # Apply valid-pixel mask
        valid = alpha_acc > 0.01
        if lpips_mask is not None:
            valid = valid & ~np.asarray(lpips_mask, dtype=bool)[:H, :W]

        if not np.any(valid):
            continue

        # Compute losses
        diff = rendered[valid] - target_img[:H, :W][valid]
        l1_loss = float(np.mean(np.abs(diff)))

        try:
            ssim_val = compute_ssim(rendered[valid][:, None, :], target_img[:H, :W][valid][:, None, :])
            ssim_loss = 1.0 - ssim_val
        except Exception:
            ssim_loss = 0.0

        view_loss = l1_weight * l1_loss + ssim_weight * ssim_loss
        total_loss += view_loss
        n_views += 1

    if n_views > 0:
        avg_loss = total_loss / n_views
        logger.info(
            "Distillation loss: %.6f (avg over %d views, L1_w=%.2f, SSIM_w=%.2f)",
            avg_loss,
            n_views,
            l1_weight,
            ssim_weight,
        )
    else:
        logger.warning("No valid views for distillation")

    # In a full implementation, we would back-propagate the loss through
    # the differentiable rasteriser and update Gaussian parameters via
    # Adam. Here we return the gaussians dict unchanged since we don't
    # have a differentiable renderer in this module.
    result = {
        "positions": positions,
        "colors": colors,
        "opacities": opacities,
        "scales": scales,
        "rotations": rotations,
    }
    if sh_coeffs is not None:
        result["sh_coeffs"] = np.asarray(sh_coeffs, dtype=np.float32)

    return result
