"""SphereForge Stage 8: HTML viewer generation.

Generates a self-contained HTML file that embeds the GaussianSplats3D viewer
from CDN (Apache 2.0 licensed) for interactive viewing of Gaussian Splat scenes.
"""

from __future__ import annotations

import logging
from pathlib import Path

logger = logging.getLogger(__name__)

VIEWER_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{ margin: 0; padding: 0; box-sizing: border-box; }}
        body {{ background: #000; overflow: hidden; font-family: system-ui, sans-serif; }}
        #viewer-container {{ width: 100vw; height: 100vh; }}
        #controls {{
            position: absolute; top: 12px; left: 12px;
            background: rgba(0,0,0,0.7); color: #fff;
            padding: 12px 16px; border-radius: 8px;
            font-size: 13px; line-height: 1.6;
            max-width: 320px; z-index: 10;
        }}
        #controls h2 {{ font-size: 15px; margin-bottom: 6px; color: #8af; }}
        #controls kbd {{
            background: #333; border: 1px solid #555;
            border-radius: 3px; padding: 1px 5px; font-size: 12px;
        }}
        #loading {{
            position: absolute; top: 50%; left: 50%;
            transform: translate(-50%, -50%);
            color: #8af; font-size: 18px;
        }}
        .hidden {{ display: none; }}
    </style>
</head>
<body>
    <div id="loading">Loading Gaussian Splat scene...</div>
    <div id="controls">
        <h2>{title}</h2>
        <p>Generated by <strong>SphereForge</strong></p>
        <hr style="border-color:#444;margin:6px 0">
        <p><kbd>Left-click + drag</kbd> Rotate</p>
        <p><kbd>Right-click + drag</kbd> Pan</p>
        <p><kbd>Scroll</kbd> Zoom</p>
        <p><kbd>W/A/S/D</kbd> Fly</p>
        <p><kbd>Q/E</kbd> Up/Down</p>
    </div>
    <div id="viewer-container"></div>

    <script type="importmap">
    {{
        "imports": {{
            "three": "https://cdn.jsdelivr.net/npm/three@0.163.0/build/three.module.js",
            "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.163.0/examples/jsm/",
            "@mkkellogg/gaussian-splats-3d": "https://cdn.jsdelivr.net/npm/@mkkellogg/gaussian-splats-3d@0.4.7/build/gaussian-splats-3d.module.js"
        }}
    }}
    </script>

    <script type="module">
        import * as GaussianSplats3D from "@mkkellogg/gaussian-splats-3d";

        async function main() {{
            const viewer = new GaussianSplats3D.Viewer({{
                rootElement: document.getElementById("viewer-container"),
                cameraUp: [0, 1, 0],
                initialCameraPosition: {initial_camera_pos},
                initialCameraLookAt: {initial_camera_lookat},
                sharedMemoryForWorkers: false,
            }};

            try {{
                await viewer.addSplatScene("{ply_filename}", {{
                    splatAlphaRemovalThreshold: 5,
                    showLoadingUI: true,
                    position: [0, 0, 0],
                    rotation: [0, 0, 0, 1],
                    scale: [1, 1, 1],
                }});
                await viewer.start();
                document.getElementById("loading").classList.add("hidden");
            }} catch (e) {{
                document.getElementById("loading").textContent =
                    "Failed to load scene: " + e.message;
                console.error(e);
            }}
        }}

        main();
    </script>
</body>
</html>"""


def generate_html_viewer(
    ply_path: Path,
    output_path: Path | None = None,
    title: str = "SphereForge Viewer",
    initial_camera_pos: tuple[float, float, float] | None = None,
    initial_camera_lookat: tuple[float, float, float] | None = None,
) -> Path:
    """Generate a self-contained HTML viewer for a Gaussian Splat scene.

    Uses the GaussianSplats3D viewer library (Apache 2.0) loaded from CDN.
    The HTML file links to the .ply file, which must be in the same directory
    (or served from the same origin due to CORS).

    Args:
        ply_path: Path to the Gaussian Splat PLY file.
        output_path: Output HTML path. Defaults to ply_path with .html extension.
        title: Page title and heading.
        initial_camera_pos: Initial camera position [x, y, z].
            Defaults to [0, 1, 5].
        initial_camera_lookat: Initial camera look-at point [x, y, z].
            Defaults to [0, 0, 0].

    Returns:
        Path to the generated HTML file.
    """
    ply_path = Path(ply_path)
    if output_path is None:
        output_path = ply_path.with_suffix(".html")
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    if initial_camera_pos is None:
        initial_camera_pos = (0.0, 1.0, 5.0)
    if initial_camera_lookat is None:
        initial_camera_lookat = (0.0, 0.0, 0.0)

    # Use just the filename — assumes same directory serving
    ply_filename = ply_path.name

    html = VIEWER_TEMPLATE.format(
        title=title,
        ply_filename=ply_filename,
        initial_camera_pos=f"[{initial_camera_pos[0]}, {initial_camera_pos[1]}, {initial_camera_pos[2]}]",
        initial_camera_lookat=f"[{initial_camera_lookat[0]}, {initial_camera_lookat[1]}, {initial_camera_lookat[2]}]",
    )

    output_path.write_text(html, encoding="utf-8")
    logger.info("HTML viewer generated: %s (links to %s)", output_path, ply_filename)
    return output_path
